import type { Config } from 'tailwindcss';

const token = (name: string) => `rgb(var(--color-${name}) / <alpha-value>)`;

export default {
  content: ['./index.html', './src/**/*.{vue,ts}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        canvas: token('bg-primary'),
        'canvas-subtle': token('bg-secondary'),
        surface: token('surface'),
        'surface-elevated': token('surface-elevated'),
        'surface-hover': token('surface-hover'),
        'border-subtle': token('border-subtle'),
        'border-active': token('border-active'),
        'text-primary': token('text-primary'),
        'text-secondary': token('text-secondary'),
        'text-muted': token('text-muted'),
        brand: token('brand-primary'),
        'brand-strong': token('brand-strong'),
        'brand-contrast': token('brand-contrast'),
        accent: token('accent-secondary'),
        success: token('success'),
        warning: token('warning'),
        danger: token('danger'),
        info: token('info'),
        overlay: token('overlay'),
        cyber: {
          bg: token('bg-primary'),
          base: token('bg-secondary'),
          surface: token('surface'),
          panel: token('surface-elevated'),
          panelHigh: token('surface-hover'),
          border: token('border-subtle'),
          outline: token('text-muted'),
          text: token('text-primary'),
          muted: token('text-secondary'),
          cyan: token('brand-primary'),
          cyanBright: token('brand-strong'),
          purple: token('accent-secondary'),
          purpleDeep: token('accent-strong'),
          emerald: token('success'),
          danger: token('danger'),
        },
      },
      fontFamily: {
        display: ['Space Grotesk', 'Segoe UI Variable Display', 'Inter', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'Segoe UI Variable Text', 'PingFang SC', 'Microsoft YaHei', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Cascadia Code', 'SFMono-Regular', 'Consolas', 'Liberation Mono', 'monospace'],
      },
      fontSize: {
        display: ['clamp(2.75rem, 7vw, 5.5rem)', { lineHeight: '0.98', letterSpacing: '-0.045em', fontWeight: '700' }],
        h1: ['clamp(2.25rem, 5vw, 3.75rem)', { lineHeight: '1.08', letterSpacing: '-0.035em', fontWeight: '700' }],
        h2: ['clamp(1.75rem, 3vw, 2.5rem)', { lineHeight: '1.16', letterSpacing: '-0.025em', fontWeight: '650' }],
        h3: ['clamp(1.25rem, 2vw, 1.625rem)', { lineHeight: '1.28', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75' }],
        body: ['1rem', { lineHeight: '1.7' }],
        small: ['0.875rem', { lineHeight: '1.6' }],
        caption: ['0.75rem', { lineHeight: '1.5', letterSpacing: '0.02em' }],
        mono: ['0.8125rem', { lineHeight: '1.55', letterSpacing: '0.025em' }],
      },
      borderRadius: {
        control: '0.625rem',
        glass: '1rem',
        panel: '1.25rem',
      },
      boxShadow: {
        soft: 'var(--shadow-soft)',
        glow: 'var(--shadow-glow)',
        elevated: 'var(--shadow-elevated)',
        focus: '0 0 0 3px rgb(var(--color-brand-primary) / 0.22)',
      },
      backdropBlur: {
        glass: '12px',
        elevated: '20px',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '240ms',
        slow: '360ms',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
        entrance: 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      maxWidth: {
        content: '80rem',
        reading: '46rem',
      },
    },
  },
  plugins: [],
} satisfies Config;
